### ISSUE TITLE
Some bag files work some don't need some insight.

### ISSUE THREAD

**Issue by rnunziata** [raulmur/ORB_SLAM2#444]
I have run orb_slam2 ros rgb against 

       skimap_ros/tiago_bar.bag

and it works find....the camera pose is tracks.
but
i run it against

    rgbd_dataset_freiburg1_floor.bag

and the camera does not track. I can filter the bag files so that only image and depth msgs are left still it works for the tiago_bar but not the other. I can see no difference that would cause one to work and the other not....baring camera parameters which I have accounted. The intrinsic parameters are not that different between the two bag files in either case. Can some explain what is happening here?

links to bag files below:

https://drive.google.com/file/d/0B02158j5inr3Tm9nQjhIQ3Fua3c/view

https://vision.in.tum.de/data/datasets/rgbd-dataset/download

Some differences in depth messages:

```
header: 
  seq: 2561
  stamp: 
    secs: 1472902312
    nsecs: 771688692
  frame_id: xtion_rgb_optical_frame
height: 480
width: 640
encoding: 16UC1
is_bigendian: 0
```

```
header: 
  seq: 7893
  stamp: 
    secs: 1305033549
    nsecs: 684985833
  frame_id: /openni_rgb_optical_frame
height: 480
width: 640
encoding: 32FC1
is_bigendian: 0
```

If I convert the taigo depth messages  from 16UC1   to   32FC1 using image_proc/metric
then ORBSLAM rgb does not work.
